-- Phase 3, stage 1: the tables money moves through on its way in and out.
--
-- attribution_addresses  a customer's deposit address (ADR-0002)
-- deposits               one incoming transfer, DETECTED .. CREDITED (state-machines.md 1)
-- withdrawals            one outgoing transfer, REQUESTED .. CONFIRMED (state-machines.md 2)
-- withdrawal_approvals   one administrator's approval; dual approval is two rows
-- sweeps                 attribution address -> treasury (JE-2)
-- outbox_events          external effects, delivered later by the worker (ADR-0007)
-- idempotency_keys       claimed Idempotency-Key headers and their responses (ADR-0007)
-- mock_chain_*           the deterministic mock chain and custody provider (ADR-0006)
--
-- Every amount column is the ledger's unit, millionths of a USDT; raw_amount
-- columns keep the chain's own integer as text. DEPOSIT_REVIEWER joins the
-- admin roles: it decides a deposit held for review and attributes one that
-- arrived unmatched. Generated by `prisma migrate diff`.
-- CreateEnum
CREATE TYPE "chain_network" AS ENUM ('BSC');

-- CreateEnum
CREATE TYPE "address_status" AS ENUM ('ACTIVE', 'RETIRED');

-- CreateEnum
CREATE TYPE "deposit_status" AS ENUM ('DETECTED', 'CONFIRMING', 'CREDITED', 'ORPHANED', 'MANUAL_REVIEW', 'UNATTRIBUTED', 'REJECTED');

-- CreateEnum
CREATE TYPE "withdrawal_status" AS ENUM ('REQUESTED', 'RISK_REVIEW', 'APPROVED', 'REJECTED', 'CANCELLED', 'BUILDING', 'BUILD_FAILED', 'SIGNING', 'SIGN_REFUSED', 'BROADCAST', 'BROADCAST_UNKNOWN', 'MANUAL_INVESTIGATION', 'CONFIRMED', 'FAILED_CONFIRMED');

-- CreateEnum
CREATE TYPE "sweep_status" AS ENUM ('PENDING', 'BROADCAST', 'CONFIRMED', 'FAILED');

-- CreateEnum
CREATE TYPE "outbox_status" AS ENUM ('PENDING', 'SENT', 'FAILED');

-- CreateEnum
CREATE TYPE "mock_transfer_outcome" AS ENUM ('BROADCAST', 'REFUSED', 'UNKNOWN_BROADCAST', 'UNKNOWN_DROPPED');

-- AlterEnum
ALTER TYPE "admin_role" ADD VALUE 'DEPOSIT_REVIEWER';

-- CreateTable
CREATE TABLE "attribution_addresses" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "network" "chain_network" NOT NULL,
    "asset" "ledger_asset" NOT NULL,
    "address" TEXT NOT NULL,
    "custody_wallet_ref" TEXT NOT NULL,
    "custody_account_ref" TEXT,
    "status" "address_status" NOT NULL DEFAULT 'ACTIVE',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "attribution_addresses_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "deposits" (
    "id" TEXT NOT NULL,
    "network" "chain_network" NOT NULL,
    "tx_hash" TEXT NOT NULL,
    "log_index" INTEGER NOT NULL,
    "block_number" BIGINT NOT NULL,
    "from_address" TEXT NOT NULL,
    "to_address" TEXT NOT NULL,
    "token_contract" TEXT NOT NULL,
    "raw_amount" TEXT NOT NULL,
    "asset" "ledger_asset" NOT NULL,
    "amount" BIGINT NOT NULL,
    "address_id" TEXT,
    "user_id" TEXT,
    "status" "deposit_status" NOT NULL DEFAULT 'DETECTED',
    "confirmations" INTEGER NOT NULL DEFAULT 0,
    "review_reason" TEXT,
    "ledger_transaction_id" TEXT,
    "correlation_id" TEXT NOT NULL,
    "detected_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "credited_at" TIMESTAMP(3),
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "deposits_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "withdrawals" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "network" "chain_network" NOT NULL,
    "asset" "ledger_asset" NOT NULL,
    "amount" BIGINT NOT NULL,
    "fee" BIGINT NOT NULL DEFAULT 0,
    "destination" TEXT NOT NULL,
    "status" "withdrawal_status" NOT NULL DEFAULT 'REQUESTED',
    "risk_score" INTEGER,
    "risk_reasons" TEXT[],
    "approvals_required" INTEGER NOT NULL DEFAULT 0,
    "tx_hash" TEXT,
    "provider_ref" TEXT,
    "block_number" BIGINT,
    "confirmations" INTEGER NOT NULL DEFAULT 0,
    "build_attempts" INTEGER NOT NULL DEFAULT 0,
    "failure_reason" TEXT,
    "hold_transaction_id" TEXT,
    "broadcast_transaction_id" TEXT,
    "settled_transaction_id" TEXT,
    "client_key" TEXT NOT NULL,
    "correlation_id" TEXT NOT NULL,
    "requested_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "broadcast_at" TIMESTAMP(3),
    "settled_at" TIMESTAMP(3),
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "withdrawals_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "withdrawal_approvals" (
    "id" TEXT NOT NULL,
    "withdrawal_id" TEXT NOT NULL,
    "admin_id" TEXT NOT NULL,
    "admin_email" TEXT NOT NULL,
    "reason" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "withdrawal_approvals_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "sweeps" (
    "id" TEXT NOT NULL,
    "address_id" TEXT NOT NULL,
    "network" "chain_network" NOT NULL,
    "asset" "ledger_asset" NOT NULL,
    "amount" BIGINT NOT NULL,
    "status" "sweep_status" NOT NULL DEFAULT 'PENDING',
    "tx_hash" TEXT,
    "provider_ref" TEXT,
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "last_error" TEXT,
    "broadcast_transaction_id" TEXT,
    "confirmed_transaction_id" TEXT,
    "correlation_id" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "sweeps_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "outbox_events" (
    "id" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "payload" JSONB NOT NULL,
    "status" "outbox_status" NOT NULL DEFAULT 'PENDING',
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "available_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "sent_at" TIMESTAMP(3),
    "last_error" TEXT,
    "correlation_id" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "outbox_events_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "idempotency_keys" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "endpoint" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "request_hash" TEXT NOT NULL,
    "response_status" INTEGER NOT NULL,
    "response_body" JSONB NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "idempotency_keys_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "mock_chain_heads" (
    "network" "chain_network" NOT NULL,
    "height" BIGINT NOT NULL DEFAULT 0,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "mock_chain_heads_pkey" PRIMARY KEY ("network")
);

-- CreateTable
CREATE TABLE "mock_chain_transfers" (
    "id" TEXT NOT NULL,
    "network" "chain_network" NOT NULL,
    "tx_hash" TEXT NOT NULL,
    "log_index" INTEGER NOT NULL,
    "block_number" BIGINT NOT NULL,
    "from_address" TEXT NOT NULL,
    "to_address" TEXT NOT NULL,
    "token_contract" TEXT NOT NULL,
    "raw_amount" TEXT NOT NULL,
    "orphaned_at_block" BIGINT,
    "tag" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "mock_chain_transfers_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "mock_custody_directives" (
    "client_ref" TEXT NOT NULL,
    "outcome" "mock_transfer_outcome" NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "mock_custody_directives_pkey" PRIMARY KEY ("client_ref")
);

-- CreateIndex
CREATE UNIQUE INDEX "attribution_addresses_network_address_key" ON "attribution_addresses"("network", "address");

-- CreateIndex
CREATE UNIQUE INDEX "attribution_addresses_user_id_network_asset_key" ON "attribution_addresses"("user_id", "network", "asset");

-- CreateIndex
CREATE INDEX "deposits_status_updatedAt_idx" ON "deposits"("status", "updatedAt");

-- CreateIndex
CREATE INDEX "deposits_user_id_detected_at_idx" ON "deposits"("user_id", "detected_at");

-- CreateIndex
CREATE INDEX "deposits_correlation_id_idx" ON "deposits"("correlation_id");

-- CreateIndex
CREATE UNIQUE INDEX "deposits_network_tx_hash_log_index_key" ON "deposits"("network", "tx_hash", "log_index");

-- CreateIndex
CREATE INDEX "withdrawals_status_updatedAt_idx" ON "withdrawals"("status", "updatedAt");

-- CreateIndex
CREATE INDEX "withdrawals_user_id_requested_at_idx" ON "withdrawals"("user_id", "requested_at");

-- CreateIndex
CREATE INDEX "withdrawals_correlation_id_idx" ON "withdrawals"("correlation_id");

-- CreateIndex
CREATE UNIQUE INDEX "withdrawals_user_id_client_key_key" ON "withdrawals"("user_id", "client_key");

-- CreateIndex
CREATE UNIQUE INDEX "withdrawal_approvals_withdrawal_id_admin_id_key" ON "withdrawal_approvals"("withdrawal_id", "admin_id");

-- CreateIndex
CREATE INDEX "sweeps_status_updatedAt_idx" ON "sweeps"("status", "updatedAt");

-- CreateIndex
CREATE INDEX "outbox_events_status_available_at_idx" ON "outbox_events"("status", "available_at");

-- CreateIndex
CREATE INDEX "outbox_events_correlation_id_idx" ON "outbox_events"("correlation_id");

-- CreateIndex
CREATE INDEX "idempotency_keys_createdAt_idx" ON "idempotency_keys"("createdAt");

-- CreateIndex
CREATE UNIQUE INDEX "idempotency_keys_user_id_endpoint_key_key" ON "idempotency_keys"("user_id", "endpoint", "key");

-- CreateIndex
CREATE INDEX "mock_chain_transfers_network_to_address_block_number_idx" ON "mock_chain_transfers"("network", "to_address", "block_number");

-- CreateIndex
CREATE INDEX "mock_chain_transfers_network_from_address_idx" ON "mock_chain_transfers"("network", "from_address");

-- CreateIndex
CREATE UNIQUE INDEX "mock_chain_transfers_network_tx_hash_log_index_key" ON "mock_chain_transfers"("network", "tx_hash", "log_index");

-- AddForeignKey
ALTER TABLE "attribution_addresses" ADD CONSTRAINT "attribution_addresses_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "deposits" ADD CONSTRAINT "deposits_address_id_fkey" FOREIGN KEY ("address_id") REFERENCES "attribution_addresses"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "deposits" ADD CONSTRAINT "deposits_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "withdrawals" ADD CONSTRAINT "withdrawals_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "withdrawal_approvals" ADD CONSTRAINT "withdrawal_approvals_withdrawal_id_fkey" FOREIGN KEY ("withdrawal_id") REFERENCES "withdrawals"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "sweeps" ADD CONSTRAINT "sweeps_address_id_fkey" FOREIGN KEY ("address_id") REFERENCES "attribution_addresses"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "idempotency_keys" ADD CONSTRAINT "idempotency_keys_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

