-- Phase 3, stage 2: the deposit pipeline.
--
-- deposits gain how they were first seen (webhook or observer) and who decided
-- a held or unattributed one; chain_observer_cursors records how far the
-- observer has scanned; DEPOSIT_CREDITED joins the notification types.
-- Generated by `prisma migrate diff`.
-- AlterEnum
ALTER TYPE "notification_type" ADD VALUE 'DEPOSIT_CREDITED';

-- AlterTable
ALTER TABLE "deposits" ADD COLUMN     "decided_at" TIMESTAMP(3),
ADD COLUMN     "decided_by" TEXT,
ADD COLUMN     "decision_reason" TEXT,
ADD COLUMN     "detected_via" TEXT NOT NULL;

-- CreateTable
CREATE TABLE "chain_observer_cursors" (
    "network" "chain_network" NOT NULL,
    "last_block" BIGINT NOT NULL,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "chain_observer_cursors_pkey" PRIMARY KEY ("network")
);

